name: Build and test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Restore the cached `target` directory
      id: cache-target-restore
      uses: actions/cache/restore@v3
      with:
        path: target
        key: target_dirs
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: Save the new `target` directory
      id: cache-target-save
      uses: actions/cache/restore@v3
      with:
        path: target
        key: target_dirs
